# Generated by Django 3.1.2 on 2020-11-23 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='adress',
        ),
        migrations.AddField(
            model_name='profile',
            name='information',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=13, verbose_name='Страна')),
                ('sity', models.CharField(max_length=20, verbose_name='Город')),
                ('post_index', models.IntegerField(blank=True, max_length=6, null=True, verbose_name='Почтовый индекс')),
                ('adress', models.CharField(max_length=50, verbose_name='Адрес доставки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adress', to='user.profile')),
            ],
        ),
    ]
