# Generated by Django 3.1.2 on 2020-11-22 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbook', '0009_auto_20201115_1933'),
        ('orders', '0002_bookincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookincart',
            name='book',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='books_in_carts', to='dbook.book'),
            preserve_default=False,
        ),
    ]
