# Generated by Django 3.1.2 on 2020-11-25 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbook', '0010_auto_20201122_1727'),
        ('user', '0004_auto_20201125_1403'),
        ('orders', '0003_bookincart_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Заказ принят'), (2, 'Заказ выполняется'), (3, 'Заказ выполнен')], default=1, verbose_name='Статус заказа')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='user.adress')),
                ('book_in_cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.bookincart')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='dbook.book')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='user.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
