# Generated by Django 3.1.2 on 2020-11-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201126_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book_in_cart',
        ),
    ]
