# Generated by Django 3.1.2 on 2020-11-26 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbook', '0010_auto_20201122_1727'),
        ('orders', '0006_remove_order_book_in_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.CreateModel(
            name='BookInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='dbook.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_in_order', to='orders.order')),
            ],
        ),
    ]
