# Generated by Django 3.1.2 on 2020-11-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201126_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.bookinorder'),
            preserve_default=False,
        ),
    ]
