# Generated by Django 3.1.2 on 2020-11-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20201128_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Order price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Заказ сформирован'), (2, 'Заказ подтвержден'), (3, 'Заказ выполняется'), (4, 'Заказ выполнен')], default=1, verbose_name='Статус заказа'),
        ),
    ]
