# Generated by Django 3.1.2 on 2020-11-28 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbook', '0011_auto_20201128_1508'),
        ('orders', '0010_auto_20201128_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinorder',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio', to='dbook.book'),
        ),
        migrations.AlterField(
            model_name='bookinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio', to='orders.order'),
        ),
    ]
