# Generated by Django 3.1.2 on 2020-11-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20201129_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='information',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
