# Generated by Django 3.1.2 on 2020-12-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Сформирован', 'Сформирован'), ('Подтвержден', 'Подтвержден'), ('Выполняется', 'Выполняется'), ('Выполнен', 'Выполнен')], default='Сформирован', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
