# Generated by Django 3.1.2 on 2020-12-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20201202_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1 - Сформирован', '1 - Сформирован'), ('2 - Подтвержден', '2 - Подтвержден'), ('3 - Выполняется', '3 - Выполняется'), ('4 - Выполнен', '4 - Выполнен')], default='1 - Сформирован', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
