# Generated by Django 3.1.2 on 2020-10-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=30, verbose_name='Автор')),
                ('author_pseudonym', models.CharField(max_length=30, verbose_name='Псевдонимы')),
                ('author_comments', models.CharField(max_length=500, verbose_name='Комментарии')),
            ],
        ),
        migrations.CreateModel(
            name='Book_series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, max_length=100, null=True, verbose_name='Книжная серия')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Жанр')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=100, verbose_name='Издательство')),
                ('publisher_desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Информация об издательстве')),
            ],
        ),
    ]
