# Generated by Django 3.1.2 on 2020-10-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_pseudonym',
            field=models.CharField(max_length=50, verbose_name='Псевдонимы'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Жанры'),
        ),
    ]
