# Generated by Django 3.1.2 on 2020-10-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0002_auto_20201018_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_comments',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_pseudonym',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Псевдонимы'),
        ),
        migrations.AlterField(
            model_name='book_series',
            name='series',
            field=models.CharField(default=0, max_length=100, verbose_name='Книжная серия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(default=0, max_length=50, verbose_name='Жанры'),
            preserve_default=False,
        ),
    ]
