# Generated by Django 3.1.2 on 2020-11-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0003_auto_20201018_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_pseudonym',
            new_name='pseudonym',
        ),
        migrations.RenameField(
            model_name='book_series',
            old_name='series',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='publisher_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='publisher',
            new_name='name',
        ),
    ]
