# Generated by Django 3.1.2 on 2020-10-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbase', '0003_auto_20201018_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200, verbose_name='Название книги')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото книги')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена книги')),
                ('publication_year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Год издания')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('bind', models.CharField(blank=True, max_length=100, null=True, verbose_name='Переплет')),
                ('form', models.CharField(blank=True, max_length=100, null=True, verbose_name='Формат')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('weigt', models.IntegerField(verbose_name='Вес книги')),
                ('age_limit', models.CharField(blank=True, max_length=3, null=True, verbose_name='Возрастные ограничения')),
                ('books_available', models.IntegerField(verbose_name='Количество книг в наличии')),
                ('active', models.BooleanField(choices=[(True, 'Доступна'), (False, 'Недостпна')], verbose_name='Доступна для заказа')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Рейтинг книги')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('change_date', models.DateField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('author', models.ManyToManyField(blank=True, null=True, to='dbase.Author', verbose_name='Авторы')),
                ('genre', models.ManyToManyField(blank=True, null=True, to='dbase.Genre', verbose_name='Жанр книги')),
                ('publisher', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.PROTECT, to='dbase.publisher', verbose_name='Издательство')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dbase.book_series', verbose_name='Книжная серия')),
            ],
        ),
    ]
