# Generated by Django 3.1.2 on 2020-10-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0003_auto_20201018_1903'),
        ('dbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, to='dbase.Author', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, to='dbase.Genre', verbose_name='Жанр книги'),
        ),
    ]
