# Generated by Django 3.1.2 on 2020-10-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbook', '0002_auto_20201020_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='weigt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес книги'),
        ),
    ]
