# Generated by Django 3.1.2 on 2020-10-24 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0003_auto_20201018_1903'),
        ('dbook', '0003_auto_20201020_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='serie',
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='dbase.book_series', verbose_name='Книжная серия'),
        ),
        migrations.AlterField(
            model_name='book',
            name='active',
            field=models.BooleanField(choices=[(True, 'Доступна'), (False, 'Недоступна')], verbose_name='Доступна для заказа'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='dbase.Author', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bind',
            field=models.CharField(default=0, max_length=100, verbose_name='Переплет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='form',
            field=models.CharField(default=0, max_length=100, verbose_name='Формат'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='books', to='dbase.Genre', verbose_name='Жанр книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0, verbose_name='Количество страниц'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.CharField(default=0, max_length=4, verbose_name='Год издания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=0, max_length=200, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='dbase.publisher', verbose_name='Издательство'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг книги'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='weigt',
            field=models.IntegerField(default=0, verbose_name='Вес книги'),
            preserve_default=False,
        ),
    ]
