# Generated by Django 3.1.2 on 2020-10-31 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbook', '0004_auto_20201024_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='weigt',
            new_name='weight',
        ),
    ]
