# Generated by Django 3.1.2 on 2020-11-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbook', '0005_auto_20201031_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='book',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/book_images', verbose_name='Фото книги'),
        ),
    ]
