# Generated by Django 3.1.2 on 2020-11-14 17:19

import dbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbook', '0006_auto_20201108_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=dbook.models.image_upload_path, verbose_name='Фото книги'),
        ),
    ]
