# Generated by Django 3.1.2 on 2020-11-15 16:33

import dbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbook', '0008_auto_20201114_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='foto',
            field=models.ImageField(blank=True, default='book_images/no_image.jpg', null=True, upload_to=dbook.models.image_upload_path, verbose_name='Фото книги'),
        ),
    ]
