# Generated by Django 3.1.2 on 2020-11-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbook', '0009_auto_20201115_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Цена книги'),
            preserve_default=False,
        ),
    ]
