# Generated by Django 3.1.2 on 2020-11-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbook', '0010_auto_20201122_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг книги'),
        ),
    ]
